[project]
name = "smart-tank"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "adafruit-ampy>=1.1.0",
    "esptool>=5.0.0",
]
